service:
  name: ${file(config.js):env.APP_NAME}-sns

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(config.js):env.region}

plugins:
  - serverless-pseudo-parameters
  - serverless-offline-sns

custom:
  serverless-offline-sns:
    port: ${file(config.js):env.snsOfflinePort}
    debug: true

resources:
  Resources:
    usersEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${file(config.js):env.usersEvent}
        TopicName: ${file(config.js):env.usersEvent}

    ticketsEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${file(config.js):env.ticketsEvent}
        TopicName: ${file(config.js):env.ticketsEvent}

    eventsEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${file(config.js):env.eventsEvent}
        TopicName: ${file(config.js):env.eventsEvent}
