service:
  name: ${file(config.js):env.gqlServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(config.js):env.region}
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/lambda/*:*:*'
    - Effect: 'Allow'
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource:
        - 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:*'
    - Effect: 'Allow'
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - '*'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
  # - serverless-plugin-tracing

custom:
  serverless-offline:
    port: ${file(config.js):env.gqlPort}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  graphql:
    name: ${file(config.js):env.gqlServiceName}-handler
    handler: src/index.graphql
    events:
      - http:
          method: post
          path: '/graphql'
      - http:
          method: get
          path: '/graphql'
