
POST http://localhost:5001/tickets
Content-Type: application/json

{
    "action": "create-ticket",
    "data": {
      "userId": "1234",
      "eventId": "7890",
      "price": "10.55"
    }
}
###
POST http://localhost:5001/tickets
Content-Type: application/json

{
    "action": "update-ticket",
    "data": {
      "userId": "1",
      "eventId": "124",
      "price": "125"
    }
}


###
https://rnyeog276i.execute-api.eu-central-1.amazonaws.com/test

###
