service:
  name: ${file(../../shared-config.js):shared.ticketServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(../../shared-config.js):shared.region}
  environment: ${file(config.js):env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - { Fn::GetAtt: [ticketsTable, Arn] }
        - { Fn::GetAtt: [eventTable, Arn] }
        - { Fn::GetAtt: [userTable, Arn] }

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    port: ${file(../../shared-config.js):shared.ticketPort}

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  dynamodb:
    start:
      port: ${file(../../shared-config.js):shared.ticketDbPort}
      migrate: true
    stages:
      - dev

functions:
  tickets:
    name: ${file(../../shared-config.js):shared.ticketsFunc}
    handler: src/index.handler
    events:
      - http:
          method: get
          path: '/tickets'

  authChecker:
    name: ticket-swap-auth-checker
    handler: src/auth/custom-authorizer.ts

  eventEventListener:
    name: ${self:service.name}-event-event-listener
    handler: src/handlers/event-event-listener.handler
    events:
      - sns:
          topicName: ${file(../../shared-config.js):shared.eventCreated}
          displayName: ${file(../../shared-config.js):shared.eventCreated}
      - sqs: # TODO: check sns vs sqs
          arn:
            Fn::GetAtt:
              - eventCreatedSQS
              - Arn
          batchSize: 1

resources:
  Resources:
    eventCreatedSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: event-created-queue-test

    ticketsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.tickets_tickets_table}
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE

        BillingMode: PAY_PER_REQUEST

    eventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.tickets_events_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST

    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.tickets_users_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST
