service:
  name: ${file(../shared-config.js):shared.gqlServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(../shared-config.js):shared.region}
  environment: ${file(config.js):env}
  role: mainRole

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: ${file(../shared-config.js):shared.gqlPort}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  graphql:
    handler: src/index.graphql
    events:
      - http:
          method: post
          path: '/graphql'
      - http:
          method: get
          path: '/graphql'
    role: mainRole

resources:
  Resources:
    mainRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ticket-swap-gql-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole

        Policies:
          - PolicyName: can-call-lambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'

                - Effect: 'Allow'
                  Action:
                    - lambda:InvokeFunction
                    - lambda:InvokeAsync
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:lambda'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'function'
                          - ${file(../shared-config.js):shared.ticketsFunc}
