service:
  name: ${file(../shared-config.js):shared.gqlServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(../shared-config.js):shared.region}
  environment: ${file(config.js):env}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: ${file(../shared-config.js):shared.gqlPort}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  graphql:
    handler: src/index.graphql
    events:
      - http:
          method: post
          path: '/graphql'
      - http:
          method: get
          path: '/graphql'
