service:
  name: ${file(config.js):env.usersServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(config.js):env.region}
  environment: ${file(config.js):env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - { Fn::GetAtt: [ticketsTable, Arn] }
        - { Fn::GetAtt: [eventsTable, Arn] }
        - { Fn::GetAtt: [usersTable, Arn] }
    - Effect: Allow
      Action:
        - sns:*
      Resource:
        - 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:*'

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline-sns
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  serverless-offline:
    port: ${file(config.js):env.usersPort}
  # move this to top level
  serverless-offline-sns:
    port: 9998
    debug: true

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  dynamodb:
    start:
      port: ${file(config.js):env.usersDbPort}
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: ${file(config.js):env.users_users_table}
            sources: ['./.seeds/users.json']
    stages:
      - dev

functions:
  users:
    name: ${file(config.js):env.usersFunc}
    handler: src/index.handler
    events:
      - http:
          method: any
          path: '/users'

  preSignUp:
    name: ${self:service.name}-pre-signup
    handler: src/pre-signup.handler
    events:
      - cognitoUserPool:
          pool: TicketSwapUserPool
          trigger: PreSignUp

resources:
  Resources:
    CognitoUserPoolTicketSwapUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service.name}-user-pool
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: true

        Policies:
          PasswordPolicy:
            MinimumLength: 6
    userClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service.name}-user-client
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPoolTicketSwapUserPool }

    userSignUpTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${file(config.js):env.userSignUpEvent}
        TopicName: ${file(config.js):env.userSignUpEvent}

    ticketsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_tickets_table}
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE

        BillingMode: PAY_PER_REQUEST

    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_events_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST

    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_users_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST
