service:
  name: ${file(../../shared-config.js):shared.usersServiceName}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(../../shared-config.js):shared.region}
  environment: ${file(config.js):env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - { Fn::GetAtt: [ticketsTable, Arn] }
        - { Fn::GetAtt: [eventsTable, Arn] }
        - { Fn::GetAtt: [usersTable, Arn] }

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    port: ${file(../../shared-config.js):shared.usersPort}

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  dynamodb:
    start:
      port: ${file(../../shared-config.js):shared.usersDbPort}
      migrate: true
    stages:
      - dev

functions:
  users:
    name: ${file(../../shared-config.js):shared.usersFunc}
    handler: src/index.handler
    events:
      - http:
          method: '*'
          path: '/users'
resources:
  Resources:
    ticketsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_tickets_table}
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE

        BillingMode: PAY_PER_REQUEST

    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_events_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST

    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.js):env.users_users_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST
